# Site settings
title: Zehua Zeng
email: fiona.zehua.zeng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zehua-zeng.github.io/" # the base hostname & protocol for your site
production_url: "https://zehua-zeng.github.io/"
github_username: zehua-zeng
# permalink removed to stop blog routes from being generated

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

sidebar-external:
  - icon: <i class="fa-regular fa-envelope"></i>
    link: mailto:fiona.zehua.zeng@gmail.com
  - icon: <i class="fa-regular fa-file-lines"></i>
    link: files/Zehua-Zeng-Resume.pdf
  - icon: <i class="fa-solid fa-graduation-cap"></i>
    link: https://scholar.google.com/citations?user=GNJPhNEAAAAJ
  - icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0002-5153-3865
  - icon: <i class="fa-brands fa-github-alt"></i>
    link: https://github.com/Zehua-Zeng
  - icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/zehuazeng/
